swagger: "2.0"

info:
  title: "API"
  description: description of api
  version: "1.0"

basePath: /api

paths:
  /addUser:
    get:
      summary: Returns a string.
      description: Optional extended description in CommonMark or HTML.
      operationId: user_api.addUser
      produces:
        - text/plain
      responses:
        200:    # status code
          description: A string
          
