version: '3.6'
services:
    device-service:
        build: .
        ports:
            - "5400:5400"
        expose:
            - "5400"
        volumes:
            - .:/code
        networks:
            - device-core-net
        container_name: device-service
networks:
  device-core-net:
    external:
      name: platform
