version: '3.7'
services:
    device-service:
        build: .
        ports:
            - 5200
        volumes:
            - .:/code

    nginx:
        image: nginx:1.15.7
        ports:
            - "8090:80"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro