swagger: "2.0"

info:
  title: "API"
  description: description of api
  version: "1.0"

basePath: /api

paths:
  /hej:
    get:
      summary: Returns a string.
      description: Optional extended description in CommonMark or HTML.
      operationId: hello.hello
      produces:
        - application/json
      responses:
        200:    # status code
          description: A string
          
