swagger: "2.0"

info:
  title: "web_app_api"
  description: description of api
  version: "1.0"

basePath: /v1

paths:
  /users/authenticate:
    post:
      summary: summary here
      description: description here
      operationId: web_app_api.post_users_authenticate
      consumes:
        - application/json
      parameters:
        - $ref: '#/parameters/postUsersAuthenticateRequestBody'
      responses:
        200:
          description: A user
        400:
          description: Bad Request
        401:
          description: Unauthorized
        404:
          description: Not Found
  /users:
    post:
      summary: summary here
      description: description here
      operationId: web_app_api.post_users
      consumes:
        - application/json
      parameters:
        - $ref: '#/parameters/postUsersRequestBody'
      responses:
        200:
          description: A user
        400:
          description: Bad Request
        401:
          description: Unauthorized
        404:
          description: Not Found
  /users/{id}:
    get:
      summary: summary here
      description: description here
      operationId: web_app_api.get_users_id
      consumes:
        - application/json
      parameters:
        - $ref: '#/parameters/id'
        - $ref: '#/parameters/getDeleteUsersRequestBody'
      responses:
        200:
          description: A user
        400:
          description: Bad Request
        401:
          description: Unauthorized
        404:
          description: Not Found
    patch:
      summary: summary here
      description: description here
      operationId: web_app_api.patch_users_id
      consumes:
        - application/json
      parameters:
        - $ref: '#/parameters/id'
        - $ref: '#/parameters/patchUsersRequestBody'
      responses:
        200:
          description: A user
        400:
          description: Bad Request
        401:
          description: Unauthorized
        404:
          description: Not Found
    delete:
      summary: summary here
      description: description here
      operationId: web_app_api.delete_users_id
      consumes:
        - application/json
      parameters:
        - $ref: '#/parameters/id'
        - $ref: '#/parameters/getDeleteUsersRequestBody'
      responses:
        200:
          description: A user
        400:
          description: Bad Request
        401:
          description: Unauthorized
        404:
          description: Not Found
  /users/{id}/devices:
    post:
      summary: summary here
        description: description here
        operationId: web_app_api.post_users_id_devices
        consumes:
          - application/json
        parameters:
          - $ref: '#/parameters/id'
          - $ref: '#/parameters/postDevicesRequestBody'
        responses:
          200:
            description: A device
          400:
            description: Bad Request
          401:
            description: Unauthorized
          404:
            description: Not Found
  /users/{id}/devices/{id}:
    get:
      summary: summary here
      description: description here
      operationId: web_app_api.get_users_user_id_devices_device_id
      consumes:
        - application/json
      parameters:
        - $ref: '#/parameters/id'
        - $ref: '#/parameters/getDeleteDevicesRequestBody'
      responses:
        200:
          description: A user
        400:
          description: Bad Request
        401:
          description: Unauthorized
        404:
          description: Not Found
    patch:
      summary: summary here
      description: description here
      operationId: web_app_api.patch_users_user_id_devices_device_id
      consumes:
        - application/json
      parameters:
        - $ref: '#/parameters/id'
        - $ref: '#/parameters/patchDevicesRequestBody'
      responses:
        200:
          description: A user
        400:
          description: Bad Request
        401:
          description: Unauthorized
        404:
          description: Not Found
    delete:
      summary: summary here
      description: description here
      operationId: web_app_api.delete_users_user_id_devices_device_id
      consumes:
        - application/json
      parameters:
        - $ref: '#/parameters/id'
        - $ref: '#/parameters/getDeleteDevicesRequestBody'
      responses:
        200:
          description: A user
        400:
          description: Bad Request
        401:
          description: Unauthorized
        404:
          description: Not Found
  /users/{id}/devices/{id}/actions:
    post:
      summary: summary here
        description: description here
        operationId: web_app_api.post_users_user_id_devices_device_id_actions
        consumes:
          - application/json
        parameters:
          - $ref: '#/parameters/id'
          - $ref: '#/parameters/postActionsRequestBody'
        responses:
          200:
            description: An action
          400:
            description: Bad Request
          401:
            description: Unauthorized
          404:
            description: Not Found
  /users/{id}/devices/{id}/actions/{id}:
    get:
      summary: summary here
        description: description here
        operationId: web_app_api.get_users_user_id_devices_device_id_actions_action_id
        consumes:
          - application/json
        parameters:
          - $ref: '#/parameters/id'
          - $ref: '#/parameters/getDeleteActionsRequestBody'
        responses:
          200:
            description: An action
          400:
            description: Bad Request
          401:
            description: Unauthorized
          404:
            description: Not Found
    patch:
      summary: summary here
        description: description here
        operationId: web_app_api.patch_users_user_id_devices_device_id_actions_action_id
        consumes:
          - application/json
        parameters:
          - $ref: '#/parameters/id'
          - $ref: '#/parameters/patchActionsRequestBody'
        responses:
          200:
            description: An action
          400:
            description: Bad Request
          401:
            description: Unauthorized
          404:
            description: Not Found
    delete:
      summary: summary here
        description: description here
        operationId: web_app_api.delete_users_user_id_devices_device_id_actions_action_id
        consumes:
          - application/json
        parameters:
          - $ref: '#/parameters/id'
          - $ref: '#/parameters/getDeleteActionsRequestBody'
        responses:
          200:
            description: An action
          400:
            description: Bad Request
          401:
            description: Unauthorized
          404:
            description: Not Found
  /users/{id}/devices/{id}/sensors:
    post:
      summary: summary here
        description: description here
        operationId: web_app_api.post_users_user_id_devices_device_id_sensors
        consumes:
          - application/json
        parameters:
          - $ref: '#/parameters/id'
          - $ref: '#/parameters/postSensorsRequestBody'
        responses:
          200:
            description: A sensor
          400:
            description: Bad Request
          401:
            description: Unauthorized
          404:
            description: Not Found
    /users/{id}/devices/{id}/sensors/{id}:
      get:
        summary: summary here
          description: description here
          operationId: web_app_api.get_users_user_id_devices_device_id_sensors_sensor_id
          consumes:
            - application/json
          parameters:
            - $ref: '#/parameters/id'
            - $ref: '#/parameters/getDeleteSensorsRequestBody'
          responses:
            200:
              description: A sensor
            400:
              description: Bad Request
            401:
              description: Unauthorized
            404:
              description: Not Found
      patch:
        summary: summary here
          description: description here
          operationId: web_app_api.patch_users_user_id_devices_device_id_sensors_sensor_id
          consumes:
            - application/json
          parameters:
            - $ref: '#/parameters/id'
            - $ref: '#/parameters/patchSensorsRequestBody'
          responses:
            200:
              description: A sensor
            400:
              description: Bad Request
            401:
              description: Unauthorized
            404:
              description: Not Found
      delete:
        summary: summary here
          description: description here
          operationId: web_app_api.delete_users_user_id_devices_device_id_sensors_sensor_id
          consumes:
            - application/json
          parameters:
            - $ref: '#/parameters/id'
            - $ref: '#/parameters/getDeleteSensorsRequestBody'
          responses:
            200:
              description: A sensor
            400:
              description: Bad Request
            401:
              description: Unauthorized
            404:
              description: Not Found

parameters:
  postUsersAuthenticateRequestBody:
    in: body
      name: postUsersAuthenticateRequestBody
      description: description here
      schema:
        type: object
        required:
          - username
          - password
        properties:
          username:
            type: string
          password:
            type: string
  id:
    in: path
    name: id
    description: an id for the resource
    type: string
    required: true
  postUsersRequestBody:
    in: body
    name: postUsersRequestBody
    description: description here
    schema:
      type: object
      required:
        - accessToken
        - data
      properties:
        accessToken:
          type: string
        data:
          type: object
          required:
            - username
            - password
          properties:
            username:
              type: string
            password:
              type: string
  patchUsersRequestBody:
    in: body
    name: patchUsersRequestBody
    description: description here
    schema:
      type: object
      required:
        - accessToken
        - data
      properties:
        accessToken:
          type: string
        data:
          type: object
          properties:
            username:
              type: string
            password:
              type: string
  getDeleteUsersRequestBody:
    in: body
    name: getDeleteUsersRequestBody
    description: description here
    schema:
      type: object
      required:
        - accessToken
      properties:
        accessToken:
          type: string
  postDevicesRequestBody:
    in: body
    name: postDevicesRequestBody
    description: description here
    schema:
      type: object
      required:
        - accessToken
        - data
      properties:
        accessToken:
          type: string
        data:
          type: object
          required:
            - deviceToken
            - name
          properties:
            deviceToken:
              type: string
            name:
              type: string
  patchDevicesRequestBody:
    in: body
    name: patchDevicesRequestBody
    description: description here
    schema:
      type: object
      required:
        - accessToken
        - data
      properties:
        accessToken:
          type: string
        data:
          type: object
          properties:
            deviceToken:
              type: string
            name:
              type: string
  getDeleteDevicesRequestBody:
    in: body
    name: getDeleteDevicesRequestBody
    description: description here
    schema:
      type: object
      required:
        - accessToken
      properties:
        accessToken:
          type: string
  postActionsRequestBody:
    in: body
    name: postActionsRequestBody
    description: description here
    schema:
      type: object
      required:
        - accessToken
        - data
      properties:
        accessToken:
          type: string
        data:
          type: object
          required:
            - name
            - prettyName
            - public
          properties:
            name:
              type: string
            prettyName:
              type: string
            public:
              type: bool
  patchActionsRequestBody:
    in: body
    name: patchActionsRequestBody
    description: description here
    schema:
      type: object
      required:
        - accessToken
        - data
      properties:
        accessToken:
          type: string
        data:
          type: object
          required:
            - operation
          properties:
            operation:
              type: string
              enum: [add, remove]
            name:
              type: string
            prettyName:
              type: string
            public:
              type: bool
            accessTokens:
              type: string
  getDeleteActionsRequestBody:
    in: body
    name: getDeleteActionsRequestBody
    description: description here
    schema:
      type: object
      required:
        - accessToken
      properties:
        accessToken:
          type: string
  postSensorsRequestBody:
    in: body
    name: postSensorsRequestBody
    description: description here
    schema:
      type: object
      required:
        - accessToken
        - data
      properties:
        accessToken:
          type: string
        data:
          type: object
          required:
            - name
            - prettyName
            - public
          properties:
            name:
              type: string
            prettyName:
              type: string
            public:
              type: bool
  patchSensorsRequestBody:
    in: body
    name: patchSensorsRequestBody
    description: description here
    schema:
      type: object
      required:
        - accessToken
        - data
      properties:
        accessToken:
          type: string
        data:
          type: object
          required:
            - operation
          properties:
            operation:
              type: string
              enum: [add, remove]
            name:
              type: string
            prettyName:
              type: string
            public:
              type: bool
            accessTokens:
              type: string
  getDeleteSensorsRequestBody:
    in: body
    name: getDeleteSensorsRequestBody
    description: description here
    schema:
      type: object
      required:
        - accessToken
      properties:
        accessToken:
          type: string
