version: '3.7'
services:
    user-service:
        build: .
        ports:
            - 5432
        volumes:
            - .:/code

    nginx:
        image: nginx:1.15.7
        ports:
            - "8085:80"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro