version: '3.7'
services:
    user-service:
        build: .
        ports:
            - "5100:5100"
        expose:
            - "5100"
        volumes:
            - .:/code
        networks:
            - user-core-net
        container_name: user-service
networks:
  user-core-net:
    external:
      name: platform
