version: '3.7'
services:
    user-service:
        build: .
        ports:
            - 5100
        volumes:
            - .:/code
        labels:
            - "traefik.frontend.rule=Host:user.localhost"