version: '3.7'
services:
    user-data-access-service:
        build: .
        ports:
            - 5300
        volumes:
            - .:/code
        labels:
            - "traefik.frontend.rule=Host:useraccess.localhost"
