version: '3.6'
services:
    sensor-service:
        build: .
        ports:
            - "5900:5900"
        expose:
            - "5900"
        volumes:
            - .:/code
        networks:
            - sensor-core-net
        container_name: sensor-service
networks:
  sensor-core-net:
    external:
      name: platform
