swagger: "2.0"

info:
  title: "API"
  description: description of api
  version: "1.0"

basePath: /api

paths:
  /users: #Hvad med username?
    get:
      summary: Returns a user.
      description: Optional extended description in CommonMark or HTML.
      operationId: user_api.get_user
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - in: body
          name: user
          description: The user to get.
          schema:
            type: object
            properties:
              username:
                type: string
              userId:
                type: string
      responses:
        200:    # status code
          description: A string
    post:
      summary: Returns a string.
      description: Optional extended description in CommonMark or HTML.
      operationId: user_api.add_user
      consumes:
        - application/json
      parameters:
        - in: body
          name: user
          description: The user to create.
          schema:
            type: object
            required:
              - username
              - password
              - access_token
            properties:
              username:
                type: string
              password:
                type: string
              access_token:
                type: string
      responses:
        200:    # status code
          description: A user
  /users/{userId}:
    patch:
      summary: update a user.
      description: Optional extended description in CommonMark or HTML.
      operationId: user_api.patch_user
      consumes:
        - application/json
      parameters:
        - in: path
          name: userId
          schema:
            type: string
          required: true
        - in: body
          name: update
          description: The information to update.
          schema:
            type: object
            properties:
              username:
                type: string
              password:
                type: string
              deviceList:
                type: string
              ruleList:
                type: string
              groupList:
                type: string
      responses:
        200:    # status code
          description: A user
    delete:
      summary: Deletes a user.
      description: Optional extended description in CommonMark or HTML.
      operationId: user_api.delete_user
      parameters:
        - in: path
          name: userId
          schema:
            type: string
          required: true
      responses:
        200:    # status code
          description: A string