version: '3.2'
services:
    web-app:
        build: .
        ports:
            - "80:5000"
        volumes:
            - .:/code
        networks:
            - platform
        container_name: web-app


networks:
    platform:
        external:
            name: platform
