swagger: "2.0"

info:
  title: "API"
  description: description of api
  version: "1.0"

basePath: /api

paths:
  /path:
    get:
      summary: summary of get endpoint
      description: description of get endpoint
      operationId: nameOfFunction
      tags:
        - tag1
      produces:
        - string
      responses:
        200:
          description: description
          schema:
            type: array
            items:
              $ref: '#/definitions/Name'
          examples:
            string:
              "Example"
        - $ref: '#/parameters/Param1'



parameters:
  Param1:
    type: string
    description: description of param1
    example: "param1"
    required: true
  Param2:
    type: string
    description: description of param2
    example: "param2"
    required: true

tags:
  - name: tag1
    description: description of tag1
  - name: tag2
    description: description of tag2

definitions:
  Name:
    type: object
    required:
      - param1
      - param2
    properties:
      param1:
        type: string
        description: description of param1
        example: "param1"
        readOnly: true
      param2:
        type: string
        description: description of param2
        example: "param2"
        readOnly: true
